@ECHO OFF
SET /P DESTINO=Ingrese el destino:
CD %DESTINO%
SET /P ARCHIVE=Ingrese la extension del archivo a buscar:
DIR *.%ARCHIVE% /B > ARCHIVOS
TYPE ARCHIVOS │ SORT
ECHO ESTOS SON TODOS LOS ARCHIVOS ENCONTRADOS
PAUSE >NUL
